siteName: 'Squareone Development Site'
baseUrl: 'http://localhost:3000'
siteDescription: |
  The site description.
broadcastMarkdown: |
  ðŸ‘‹ Hello world! I'm here to tell you about something important.
semaphoreUrl: 'https://data-dev.lsst.cloud/semaphore'
