[project]
title = "Squareone"
copyright = "2021-2023 Association of Universities for Research in Astronomy, Inc. (AURA)"
base_url = "https://squareone.lsst.io"
github_url = "https://github.com/lsst-sqre/squareone"
version = "current"

[sphinx]
rst_epilog_file = "_rst_epilog.rst"
nitpick_ignore = [["py:class", "pybtex.style.formatting.plain.Style"]]
extensions = ["sphinx-jsonschema"]

[sphinx.linkcheck]
ignore = [
    "https://jira.lsstcorp.org/browse/",
    "https://github.com/organizations/lsst-sqre/settings/apps/squareone-ci"
]
